version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./apps/api:/app/apps/api
    environment:
      - DATABASE_URL:postgresql://postgres:postgres@localhost:5432/platform?schema=public
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=platform
