FROM node:16-alpine

WORKDIR /app

COPY package.json ./

COPY pnpm-lock.yaml ./

RUN npm install pnpm -g

RUN pnpm install

COPY . .

COPY ./prisma ./

RUN pnpm prisma-generate

EXPOSE 3000

CMD [ "pnpm", "dev" ]