version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:3000
  db:
    image: postgres
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
volumes:
  pgdata:
