version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 3000:3000
  db:
    image: postgres
    ports:
      - 5432:5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
volumes:
  pgdata:
