FROM node:16-alpine

WORKDIR /app

RUN npm install pnpm -g

COPY apps/api/package.json apps/api/package.json
COPY apps/api/prisma apps/api/prisma

COPY pnpm-lock.yaml pnpm-lock.yaml
COPY pnpm-workspace.yaml pnpm-workspace.yaml
COPY package.json package.json

RUN pnpm install
RUN pnpm --filter api prisma generate

COPY apps/api apps/api

EXPOSE 8000

CMD [ "pnpm", "--filter", "api", "dev" ]